name: prevent
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  flutter_local_notifications: 1.3.0

  path_provider: ^1.6.14
  flutter_isolate: ^1.0.0+14
  workmanager: ^0.2.0
  # local_notifications: 0.0.5
  # workmanager: ^0.2.3
  # background_fetch: '^0.5.1'

dev_dependencies:
  flutter_test:
    sdk: flutter
  dio: ^3.0.9
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.8.0
  flutter_secure_storage: ^3.3.3
  get_storage: ^1.2.1
  string_validator: ^0.1.3
  rounded_loading_button: ^1.0.0
  masked_text: ^0.0.6
  flutter_advanced_networkimage: ^0.7.0
  rflutter_alert: ^1.0.2
  speech_to_text: ^1.1.0
  camera: ^0.5.2+1
  flutter_spinkit: ^4.1.1
  flutter_launcher_icons: ^0.7.5
  custom_switch: ^0.0.1
  audioplayers: ^0.13.5
  http: ^0.12.0
  mqtt_client: ^5.6.3
  date_picker_timeline:
    git:
      url: git://github.com/Glauber26/DatePickerTimelineFlutter.git
  geolocator: ^5.3.0

  


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon.png"
  image_path_android: "assets/icon.png"
  adaptive_icon_background: "assets/background.png"
  adaptive_icon_foreground: "assets/foreground.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/manuel.png
    - assets/mic.png
    - assets/mic_off.png
    - assets/camera.png
    - assets/icon.png
    - assets/calendar.png
    - assets/remedioadd.png
    - assets/remedio.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
